import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Footer from '../components/footer'
import Notepad from '../components/notepad'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Notepadify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/98.css"
        />

      </Head>

      <main class="window main-container">
        <Header />
        <Notepad />
        <Footer />
      </main>
    </div>
  )
}
