# Generated by Django 4.0.3 on 2022-11-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uuid',
            field=models.TextField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
