# Generated by Django 4.0.3 on 2022-11-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_uuid_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.TextField(default='add4651', editable=False, max_length=8, unique=True),
        ),
    ]
