# Generated by Django 4.0.3 on 2022-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_note_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.TextField(default='2391ae74', editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
