# Generated by Django 4.0.3 on 2022-11-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default='6a18a6d1', editable=False, primary_key=True, serialize=False),
        ),
    ]
