# Generated by Django 4.0.3 on 2022-11-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_id_alter_note_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.TextField(default='e69b3af3', editable=False, max_length=8),
        ),
    ]
