# Generated by Django 4.0.3 on 2022-11-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_note_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='online_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.TextField(default='45fc821c', editable=False, max_length=8, unique=True),
        ),
    ]
